/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShadowSwapOTCInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOffer"
      | "createOffer"
      | "getOffer"
      | "getOfferCount"
      | "takeOffer"
      | "tradeCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OfferCancelled" | "OfferCreated" | "OfferTaken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOffer",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOfferCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "takeOffer",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeCount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOfferCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "takeOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tradeCount", data: BytesLike): Result;
}

export namespace OfferCancelledEvent {
  export type InputTuple = [offerId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [offerId: bigint, seller: string];
  export interface OutputObject {
    offerId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferCreatedEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    seller: AddressLike,
    sellToken: AddressLike,
    buyToken: AddressLike,
    pricePerUnit: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    seller: string,
    sellToken: string,
    buyToken: string,
    pricePerUnit: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    seller: string;
    sellToken: string;
    buyToken: string;
    pricePerUnit: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferTakenEvent {
  export type InputTuple = [offerId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [offerId: bigint, buyer: string];
  export interface OutputObject {
    offerId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShadowSwapOTC extends BaseContract {
  connect(runner?: ContractRunner | null): ShadowSwapOTC;
  waitForDeployment(): Promise<this>;

  interface: ShadowSwapOTCInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOffer: TypedContractMethod<
    [offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOffer: TypedContractMethod<
    [
      sellToken: AddressLike,
      buyToken: AddressLike,
      pricePerUnit: BigNumberish,
      encAmount: BytesLike,
      proof: BytesLike,
      expiry: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getOffer: TypedContractMethod<
    [offerId: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        seller: string;
        sellToken: string;
        buyToken: string;
        pricePerUnit: bigint;
        expiry: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getOfferCount: TypedContractMethod<[], [bigint], "view">;

  takeOffer: TypedContractMethod<
    [offerId: BigNumberish, encBuyAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  tradeCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOffer"
  ): TypedContractMethod<[offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOffer"
  ): TypedContractMethod<
    [
      sellToken: AddressLike,
      buyToken: AddressLike,
      pricePerUnit: BigNumberish,
      encAmount: BytesLike,
      proof: BytesLike,
      expiry: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOffer"
  ): TypedContractMethod<
    [offerId: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        seller: string;
        sellToken: string;
        buyToken: string;
        pricePerUnit: bigint;
        expiry: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOfferCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "takeOffer"
  ): TypedContractMethod<
    [offerId: BigNumberish, encBuyAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tradeCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "OfferCancelled"
  ): TypedContractEvent<
    OfferCancelledEvent.InputTuple,
    OfferCancelledEvent.OutputTuple,
    OfferCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OfferCreated"
  ): TypedContractEvent<
    OfferCreatedEvent.InputTuple,
    OfferCreatedEvent.OutputTuple,
    OfferCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OfferTaken"
  ): TypedContractEvent<
    OfferTakenEvent.InputTuple,
    OfferTakenEvent.OutputTuple,
    OfferTakenEvent.OutputObject
  >;

  filters: {
    "OfferCancelled(uint256,address)": TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;
    OfferCancelled: TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;

    "OfferCreated(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      OfferCreatedEvent.InputTuple,
      OfferCreatedEvent.OutputTuple,
      OfferCreatedEvent.OutputObject
    >;
    OfferCreated: TypedContractEvent<
      OfferCreatedEvent.InputTuple,
      OfferCreatedEvent.OutputTuple,
      OfferCreatedEvent.OutputObject
    >;

    "OfferTaken(uint256,address)": TypedContractEvent<
      OfferTakenEvent.InputTuple,
      OfferTakenEvent.OutputTuple,
      OfferTakenEvent.OutputObject
    >;
    OfferTaken: TypedContractEvent<
      OfferTakenEvent.InputTuple,
      OfferTakenEvent.OutputTuple,
      OfferTakenEvent.OutputObject
    >;
  };
}
