/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WrappedConfidentialTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialBalanceOf"
      | "confidentialTotalSupply"
      | "confidentialTransfer(address,bytes32,bytes)"
      | "confidentialTransfer(address,bytes32)"
      | "confidentialTransferAndCall(address,bytes32,bytes)"
      | "confidentialTransferAndCall(address,bytes32,bytes,bytes)"
      | "confidentialTransferFrom(address,address,bytes32,bytes)"
      | "confidentialTransferFrom(address,address,bytes32)"
      | "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)"
      | "confidentialTransferFromAndCall(address,address,bytes32,bytes)"
      | "contractURI"
      | "decimals"
      | "finalizeUnwrap"
      | "inferredTotalSupply"
      | "isOperator"
      | "maxTotalSupply"
      | "name"
      | "onTransferReceived"
      | "setOperator"
      | "supportsInterface"
      | "symbol"
      | "underlying"
      | "unwrap(address,address,bytes32,bytes)"
      | "unwrap(address,address,bytes32)"
      | "unwrapRequester"
      | "wrap"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialTransfer"
      | "OperatorSet"
      | "UnwrapFinalized"
      | "UnwrapRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,bytes32,bytes)",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,bytes32)",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes)",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes,bytes)",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFrom(address,address,bytes32,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFrom(address,address,bytes32)",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractURI",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeUnwrap",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inferredTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onTransferReceived",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "underlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unwrap(address,address,bytes32,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrap(address,address,bytes32)",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrapRequester",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wrap",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferAndCall(address,bytes32,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFrom(address,address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFrom(address,address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFromAndCall(address,address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeUnwrap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inferredTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onTransferReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "underlying", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unwrap(address,address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unwrap(address,address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unwrapRequester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;
}

export namespace ConfidentialTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BytesLike
  ];
  export type OutputTuple = [from: string, to: string, amount: string];
  export interface OutputObject {
    from: string;
    to: string;
    amount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorSetEvent {
  export type InputTuple = [
    holder: AddressLike,
    operator: AddressLike,
    until: BigNumberish
  ];
  export type OutputTuple = [holder: string, operator: string, until: bigint];
  export interface OutputObject {
    holder: string;
    operator: string;
    until: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrapFinalizedEvent {
  export type InputTuple = [
    receiver: AddressLike,
    encryptedAmount: BytesLike,
    plaintextAmount: BigNumberish
  ];
  export type OutputTuple = [
    receiver: string,
    encryptedAmount: string,
    plaintextAmount: bigint
  ];
  export interface OutputObject {
    receiver: string;
    encryptedAmount: string;
    plaintextAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrapRequestedEvent {
  export type InputTuple = [receiver: AddressLike, amount: BytesLike];
  export type OutputTuple = [receiver: string, amount: string];
  export interface OutputObject {
    receiver: string;
    amount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WrappedConfidentialToken extends BaseContract {
  connect(runner?: ContractRunner | null): WrappedConfidentialToken;
  waitForDeployment(): Promise<this>;

  interface: WrappedConfidentialTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  confidentialTotalSupply: TypedContractMethod<[], [string], "view">;

  "confidentialTransfer(address,bytes32,bytes)": TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransfer(address,bytes32)": TypedContractMethod<
    [to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransferAndCall(address,bytes32,bytes)": TypedContractMethod<
    [to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransferAndCall(address,bytes32,bytes,bytes)": TypedContractMethod<
    [
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFrom(address,address,bytes32,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFrom(address,address,bytes32)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "confidentialTransferFromAndCall(address,address,bytes32,bytes)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  contractURI: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  finalizeUnwrap: TypedContractMethod<
    [unwrapRequestId: BytesLike, decryptedAmountAndProof: BytesLike],
    [void],
    "nonpayable"
  >;

  inferredTotalSupply: TypedContractMethod<[], [bigint], "view">;

  isOperator: TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [boolean],
    "view"
  >;

  maxTotalSupply: TypedContractMethod<[], [bigint], "view">;

  name: TypedContractMethod<[], [string], "view">;

  onTransferReceived: TypedContractMethod<
    [
      arg0: AddressLike,
      from: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, until: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  underlying: TypedContractMethod<[], [string], "view">;

  "unwrap(address,address,bytes32,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "unwrap(address,address,bytes32)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;

  unwrapRequester: TypedContractMethod<
    [unwrapAmount: BytesLike],
    [string],
    "view"
  >;

  wrap: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialTotalSupply"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,bytes32,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,bytes32)"
  ): TypedContractMethod<
    [to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferAndCall(address,bytes32,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferAndCall(address,bytes32,bytes,bytes)"
  ): TypedContractMethod<
    [
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFrom(address,address,bytes32,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFrom(address,address,bytes32)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFromAndCall(address,address,bytes32,bytes,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFromAndCall(address,address,bytes32,bytes)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeUnwrap"
  ): TypedContractMethod<
    [unwrapRequestId: BytesLike, decryptedAmountAndProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "inferredTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isOperator"
  ): TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onTransferReceived"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      from: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, until: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "underlying"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unwrap(address,address,bytes32,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unwrap(address,address,bytes32)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unwrapRequester"
  ): TypedContractMethod<[unwrapAmount: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "wrap"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ConfidentialTransfer"
  ): TypedContractEvent<
    ConfidentialTransferEvent.InputTuple,
    ConfidentialTransferEvent.OutputTuple,
    ConfidentialTransferEvent.OutputObject
  >;
  getEvent(
    key: "OperatorSet"
  ): TypedContractEvent<
    OperatorSetEvent.InputTuple,
    OperatorSetEvent.OutputTuple,
    OperatorSetEvent.OutputObject
  >;
  getEvent(
    key: "UnwrapFinalized"
  ): TypedContractEvent<
    UnwrapFinalizedEvent.InputTuple,
    UnwrapFinalizedEvent.OutputTuple,
    UnwrapFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "UnwrapRequested"
  ): TypedContractEvent<
    UnwrapRequestedEvent.InputTuple,
    UnwrapRequestedEvent.OutputTuple,
    UnwrapRequestedEvent.OutputObject
  >;

  filters: {
    "ConfidentialTransfer(address,address,bytes32)": TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;
    ConfidentialTransfer: TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;

    "OperatorSet(address,address,uint48)": TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;
    OperatorSet: TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;

    "UnwrapFinalized(address,bytes32,uint256)": TypedContractEvent<
      UnwrapFinalizedEvent.InputTuple,
      UnwrapFinalizedEvent.OutputTuple,
      UnwrapFinalizedEvent.OutputObject
    >;
    UnwrapFinalized: TypedContractEvent<
      UnwrapFinalizedEvent.InputTuple,
      UnwrapFinalizedEvent.OutputTuple,
      UnwrapFinalizedEvent.OutputObject
    >;

    "UnwrapRequested(address,bytes32)": TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
    UnwrapRequested: TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
  };
}
